const types = {
  UPDATE_USER_INFO: 'UPDATE_USER_INFO', // 更新用户数据
  DELETE_USER_INFO: 'DELETE_USER_INFO', // 清空用户数据
  CHANGE_CURRENT_SITE: 'CHANGE_CURRENT_SITE', // 修改当前网站数据
  CHANGE_CURRENT_ROLE: 'CHANGE_CURRENT_ROLE', // 修改当前角色数据
  CHANGE_CURRENT_MENULIST: 'CHANGE_CURRENT_MENULIST', // 修改当前菜单数据
  CHANGE_CURRENT_PATH_RECODE: 'CHANGE_CURRENT_PATH_RECODE', // 修改当前访问路径记录
  CHANGE_CURRENT_MENUID: 'CHANGE_CURRENT_MENUID', // 修改当前菜单ID
  CHANGE_KEEP_ALIVE: 'CHANGE_KEEP_ALIVE' // 当前缓存组件列表
}

export default types
